name: Terraform CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  terraform:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::533267284248:role/CI-CD-FLOW
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Debug token length
        run: |
          echo "Length of AMPLIFY_GITHUB_TOKEN: ${#AMPLIFY_GITHUB_TOKEN}"
        env:
          AMPLIFY_GITHUB_TOKEN: ${{ secrets.AMPLIFY_GITHUB_TOKEN }}

      - name: Terraform plan
        run: |
          terraform plan -input=false \
            -var github_token="${{ secrets.AMPLIFY_GITHUB_TOKEN }}" \
            -var db_password="${{ secrets.DB_PASSWORD }}" \
            -var ecs_execution_role_arn="${{ secrets.ECS_EXECUTION_ROLE_ARN }}"

      - name: Terraform apply
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
          terraform apply -auto-approve -input=false \
            -var github_token="${{ secrets.AMPLIFY_GITHUB_TOKEN }}"\
            -var db_password="${{ secrets.DB_PASSWORD }}" \
            -var ecs_execution_role_arn="${{ secrets.ECS_EXECUTION_ROLE_ARN }}"
